### ISSUE TITLE
Capabilities Error

### ISSUE THREAD

**Issue by b5019628** [NullArray/DorkNet#10]
Using Selenium 3.7.0 and Firefox Esr or even Firefox I get the following; (also got a friend to run and same error.)

Traceback (most recent call last):
  File "dorknet.py", line 154, in <module>
    proc_one = search()
  File "dorknet.py", line 107, in search
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unable to find a matching set of capabilities

**Comment by b5019628** [comment]
Tried quite a bit on Kali but could never get it working. I've done a completely fresh install of Ubuntu to test on. Using the Gecko-Setup.sh gives "./gecko-setup.sh: line 50: syntax error near unexpected token `}'
./gecko-setup.sh: line 50: `}'".

I've opened the setup file and used the wget link in there to install Geckodriver then used the commands following it. Reverted Firefox to version 50, used requirements.txt to install everything and I'm still getting the error. It also doesn't work with an updated version of Firefox.

Firefox = 50
Geckodriver  = 0.23.0
Blessings = 1.7
Python = 2.7
Selenium = 3.14.1

Get the following:

[+]Would you like DorkNet to proxy it's connection to the search engine?
[Y]es/[N]o: n

[+]Establishing unproxied connection...

Traceback (most recent call last):
  File "./dorknet.py", line 154, in <module>
    proc_one = search()
  File "./dorknet.py", line 107, in search
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
