### ISSUE TITLE
Captcha Issues

### ISSUE THREAD

**Issue by Astroida** [NullArray/DorkNet#15]
Hi @NullArray, having issues with the Google captcha when using DorkNet. When it gets to the captcha screen, after about 5-10 seconds the tool crashes and I am unable to even complete the captcha. This is the output I get:

`Traceback (most recent call last):
  File "./dorknet.py", line 180, in <module>
    proc_one = search()
  File "./dorknet.py", line 145, in search
    elem.clear()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 95, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidElementStateException: Message: Unable to clear element that cannot be edited: <input name="q" type="hidden">`

Looks to be an issue interacting with the q element from the captcha.

**Comment by Astroida** [comment]
Sorry, my original post missed a part of the error after 'cannot be edited'.

selenium.common.exceptions.InvalidElementStateException: Message: Unable to clear element that cannot be edited: _**<input name="q" type="hidden">**_

**Comment by NullArray** [comment]
Yeah, the q element is only present on the Google search page. After the latest update i committed to the repo i have been having more trouble with captchas as well. A stop gap measure could be to have a small list of proxies available, so you can switch on IP before Google starts to complain.

To that end you may find this wrapper i wrote helpful. (Link to Wrapper)[https://gist.github.com/NullArray/35e3d894fe896ee1d7d8088a3d8175b7]

Also, it may interest you to know i've been looking into means of bypassing captcha, for a new DorkNet update.
