### ISSUE TITLE
Error in Kali Linux

### ISSUE THREAD

**Issue by batutahibnu17** [NullArray/DorkNet#7]
[+]Would you like DorkNet to proxy it's connection to the search engine?
[Y]es/[N]o: y

[+]Please enter the proxy host IP: ***.***.***.***
[+]Please enter the proxy port: *****
[+]Proxy host set to: ***.***.***.***
[+]Proxy port set to: *****

[+]Establishing connection...
Traceback (most recent call last):
  File "dorknet.py", line 154, in <module>
    proc_one = search()
  File "dorknet.py", line 151, in search
    driver.quit()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 199, in quit
    RemoteWebDriver.quit(self)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 691, in quit
    self.execute(Command.QUIT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: quit

Hy. I got these error. Im using Kali Linux. :)

**Comment by NullArray** [comment]
Please update your Geckodriver to the latest release.

https://github.com/NullArray/DorkNet/issues/10
